name: run test on python

on:
  pull_request:
    branches:
      - main

jobs:
  push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run docker compose
        run: docker-compose run test
